### PR TITLE
Improve code for K lookup to increase achievable clock speed.

### PR DESCRIPTION
**Pull request by makomk**
Hi. This patch improves the way the values of K and K_next are looked up, hopefully allowing faster clock speeds. (I'm seeing successful synthesis at 100MHz with LOOP_LOG2=1 on XC6SLX75 and am hoping for a similar improvement for the fully unrolled design on XC6SLX150). Obviously I can't test this on a real FPGA or synthesize the design for XC6SLX150 though.

I'd be grateful if you could check this works for LOOP_LOG2=0 and 1, and if so merge it.

Aidan.

### CODE REVIEW

**Comment by progranism** [comment]
Looks like some good work there, Aidan :)

Just a few questions/thoughts:

1) So you removed the USE_RAM_FOR_KS configuration option. Is that because
you feel it should always be on in general, or because LX150_makomk_Test is
Xilinx specific at the moment (and so it should always be on)?

2) I have a feeling (NUM_ROUNDS/LOOP) should actually be (64/LOOP), but my
head is a little tired at the moment so I didn't think that all the way
through. It doesn't make much difference, because NUM_ROUNDS is either 64,
or it's 61 when fully unrolled in which case that portion of the calculation
is optimized out anyway.

3) Un-related to this commit: It should be possible to have NUM_ROUNDS=62
for LOOP_LOG2=1 on the second sha256_transform. It makes sense
theoretically, but I am not sure if it would break sha256_transform for some
reason.

Thank you for the improvements, and I will try to test and merge your code
soon.

~fpgaminer

**Comment by makomk** [comment]
Thanks! Some brief-ish explanation, mostly rewritten after I lost the first lot to an ill-timed GPU hang (I'm sure the original version was better):

re 1, I'm planning on getting rid of USE_RAM_FOR_KS in my version of the code with tweaked unrolling in favour of these changes - it's unnecessary code duplication and Quartus II seems happy with the same code as Xilinx here. I've merged exactly this change to my mainly Altera-targetted partial-unroll-opt branch. (None of this should be merged to DE115_makomk_mod yet; the feedback changes cause reduced clock speed and increased resource usage at LOOP_LOG2=0 on Cyclone IV.)

re 2, I have no idea because I'm not sure how to handle NUM_ROUNDS != 64 in this case. If we change it so that on every pass through the pipeline does one less round, (NUM_ROUNDS/LOOP) is correct and (64/LOOP) is incorrect - the first pipeline stage should alternate between rounds 0 and 31 and the last between 30 and 61. Of course there are other unrelated problems with this approach.

re 3, it will break stuff. If you change it so that each pass through the pipeline does 31 rounds of SHA-256, which I'm guessing is what you're suggesting, the results of computing those rounds on each piece of data will be available to feed back into the hasher pipeline exactly 32 clock cycles after the original data was fed in - and currently the code wants to feed in a fresh piece of data on that clock cycle, not feed back an old one.

Even stuck at NUM_ROUNDS=64, this code is still a lot more resource efficient for LOOP_LOG2=1 than the old code with NUM_ROUNDS=62 on uut2 anyway.

**Comment by makomk** [comment]
Also, as per my comment on the forum thread you'll probably need the one-line change I just pushed to reach 100 MHz wit LOOP_LOG2=1. Sorry.

**Comment by progranism** [comment]
Done and done. I love github's auto-merge :D

Thanks again for the improvement makomk!

**Pull request merged**
